prefix dcat: <http://www.w3.org/ns/dcat#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix void: <http://rdfs.org/ns/void#>
PREFIX kgi: <http://ns.inria.fr/kg/index#>
CONSTRUCT {
  kgi:catalogRoot dcat:dataset ?item .
  ?item a dcat:Dataset ;
     void:sparqlEndpoint ?value ;
     rdfs:label ?itemLabel .
} WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE]". }
  {
    SELECT DISTINCT ?item ?value WHERE {
      ?item p:P5305 ?statement0.
      ?statement0 (ps:P5305) ?value.
    }
  }
}
