PREFIX kgi: <http://ns.inria.fr/kg/index#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

CONSTRUCT {
  kgi:catalog a dcat:Catalog ;
    dcat:dataset ?kbNode .
    ?kbNode void:sparqlEndpoint ?endpointUrl .
} WHERE {
GRAPH ?g {
  ?kb void:sparqlEndpoint ?endpointUrl .
  VALUES ?endpointUrl {
    <https://www.ebi.ac.uk/rdf/services/sparql>
    <http://lov.okfn.org/dataset/lov/sparql>
    <http://opencitations.net/sparql>
    <http://agrold.southgreen.fr/sparql>
    <http://geco.ecophytopic.fr:8890/sparql>
    <https://sophox.org/sparql>
    <http://landregistry.data.gov.uk/landregistry/query>
    <https://ico.iate.inra.fr/fuseki/annotation/query>
    <https://ico.iate.inra.fr/fuseki/ontology/query>
    <http://data.odw.tw/sparql>
    <http://data.bnf.fr/sparql>
    <https://dati.camera.it/sparql>
    <https://bnb.data.bl.uk/sparql>
    <https://zbw.eu/beta/sparql/gnd/query>
    <https://hunter-cuny.eagle-i.net/sparqler/sparql>
    <https://ohsu.eagle-i.net/sparqler/sparql>
    <http://slod.fiz-karlsruhe.de/sparql>
    <http://bnb.data.bl.uk/sparql>
    <http://data.mimo-db.eu/sparql>
    <https://uccaribe.eagle-i.net/sparqler/sparql>
    <http://utep.eagle-i.net/sparqler/sparql>
    <http://tsu.eagle-i.net/sparqler/sparql>
    <http://lod.sztaki.hu/sparql>
    <http://sparql.openlifedata.org/>
    <https://dbmi-icode-01.dbmi.pitt.edu/sparql>
    <https://msm.eagle-i.net/sparqler/sparql>
    <https://cedropendata.mfcr.cz/c3lod/cedr/sparql>
    <http://zbw.eu/beta/sparql/gnd/query>
    <https://linkeddata.uriburner.com/sparql>
    <https://sparql.orthodb.org/sparql>
    <http://uriburner.com/sparql/>
    <https://utep.eagle-i.net/sparqler/sparql>
    <http://cdrewu.eagle-i.net/sparqler/sparql>
    <https://cau.eagle-i.net/sparqler/sparql>
    <https://cdrewu.eagle-i.net/sparqler/sparql>
    <http://data.persee.fr/sparql>
    <http://sparql.agroportal.lirmm.fr/sparql/>
    <https://lod.nl.go.kr/sparql>
    <https://opendata.aragon.es/sparql>
    <https://rpp-opendata.egon.gov.cz/odrpp/sparql>
    <http://dbtune.org/magnatune/sparql>
    <https://cs.dbpedia.org/sparql>
    <https://aopwiki.rdf.bigcat-bioinformatics.org/sparql>
    <https://tuskegee.eagle-i.net/sparqler/sparql>
    <https://data.muziekweb.nl/MuziekwebOrganization/Muziekweb/sparql/Muziekweb>
    <https://sparql.uniprot.org/sparql>
    <https://ts.glycosmos.org/sparql>
    <http://premon.fbk.eu/sparql>
    <http://data.archiveshub.ac.uk/sparql>
    <http://vocabs.ardc.edu.au/repository/api/sparql/csiro_international-chronostratigraphic-chart_geologic-time-scale-2020>
    <https://alaska.eagle-i.net/sparqler/sparql>
    <https://famu.eagle-i.net/sparqler/sparql>
    <https://glyconnect.expasy.org/sparql>
    <http://upr.eagle-i.net/sparqler/sparql>
    <http://cultura.linkeddata.es/sparql>
    <https://montana.eagle-i.net/sparqler/sparql>
    <http://dati.isprambiente.it/sparql>
    <http://howard.eagle-i.net/sparqler/sparql>
    <http://sparql.odw.tw>
    <https://upr.eagle-i.net/sparqler/sparql>
    <http://semantic.eea.europa.eu/sparql>
    <https://semantic.eea.europa.eu/sparql>
    <http://patho.phenomebrowser.net/sparql/>
    <https://zbw.eu/beta/sparql/stwv/query>
    <https://lod.abes.fr/sparql>
    <http://sparql.archives-ouvertes.fr/sparql>
    <https://datos.gob.es/virtuoso/sparql>
    <http://data.nationallibrary.fi/bib/sparql>
    <https://zbw.eu/beta/sparql/stw/query>
    <https://datos-abertos.galiciana.gal/pt/sparql>
    <https://lingualibre.fr/bigdata/namespace/wdq/sparql>
    <http://data.cervantesvirtual.com/openrdf-sesame/repositories/data>
    <http://data.archaeologydataservice.ac.uk/sparql/repositories/archives>
    <https://linkeddata1.calcul.u-psud.fr/sparql>
    <https://zbw.eu/beta/sparql/econ_pers/query>
    <https://xn--slovnk-7va.gov.cz/sparql>
    <http://quantum.agroparistech.fr/graphdb/repositories/Composite_making_process>
    <https://data.cssz.cz/sparql>
    <http://ma-graph.org/sparql>
    <http://linkedgeodata.org/sparql>
    <https://rdf.insee.fr/sparql>
    <http://linkedlifedata.com/sparql>
    <http://sparql.orthodb.org/sparql>
    <http://data.cervantesvirtual.com/bvmc-lod/repositories/data>
    <http://cr.eionet.europa.eu/sparql>
    <http://apps.morelab.deusto.es/labman/sparql>
    <http://linkeddata.finki.ukim.mk/sparql>
    <http://www.icane.es/opendata/sparql>
    <http://sparql.nibb.ac.jp/sparql>
    <https://lov.linkeddata.es/dataset/lov/sparql>
    <https://query.wikidata.org/sparql>
    <https://id.nlm.nih.gov/mesh/sparql>
    <https://es.dbpedia.org/sparql>
    <https://slod.fiz-karlsruhe.de/sparql>
    <https://www.genome.jp/sparql/linkdb>
    <https://data.escr.fr/sparql>
    <https://www.orkg.org/orkg/triplestore>
    <http://id.sgcb.mcu.es/sparql>
    <https://data.ordnancesurvey.co.uk/datasets/boundary-line/apis/sparql>
    <https://rdf.pathwaycommons.org/sparql/>
    <https://www.govdata.de/sparql>
    <https://api.parliament.uk/sparql>
    <https://data.ordnancesurvey.co.uk/datasets/50k-gazetteer/apis/sparql>
    <http://edan.si.edu/saam/sparql>
    <http://vocabs.ands.org.au/repository/api/sparql/ga_geologic-unit-type_v0-1>
    <https://data.idref.fr/sparql>
    <http://sparql.odw.tw/>
    <https://www.foodie-cloud.org/sparql>
    <http://dbtune.org/jamendo/sparql>
    <http://dbtune.org/bbc/peel/sparql>
    <https://data.epo.org/linked-data/query>
    <http://dati.camera.it/sparql>
    <https://sparql.nextprot.org/>
    <http://hkcan.julac.org/lod/sparql>
    <http://sparql.europeana.eu/>
    <http://rdf.pathwaycommons.org/sparql/>
    <http://digital-agenda-data.eu/data/sparql>
    <https://fuseki.gwascentral.org/gc/query>
    <https://sparql.rhea-db.org/sparql>
    <http://www.genome.jp/sparql/linkdb>
    <http://vocabs.ands.org.au/repository/api/sparql/anzsrc-for>
    <https://data.gov.cz/sparql>
    <https://data.ordnancesurvey.co.uk/datasets/code-point-open/apis/sparql>
    <http://lod.nl.go.kr/sparql>
    <https://jpsearch.go.jp/rdf/sparql/>
    <https://jsu.eagle-i.net/sparqler/sparql>
    <https://tsu.eagle-i.net/sparqler/sparql>
    <https://data.ordnancesurvey.co.uk/datasets/opennames/apis/sparql>
    <http://api.finto.fi/sparql>
    <http://lod.xdams.org/sparql>
    <http://affymetrix.bio2rdf.org/sparql>
    <http://www.scholarlydata.org/sparql>
    <http://data.colinda.org/endpoint.php>
    <https://forum.semantic-metabolomics.fr/sparql/>
    <http://dbtune.org/musicbrainz/sparql>
    <http://data.culture.fr/thesaurus/sparql>
    <https://sparql.crssnky.xyz/spql/imas/query>
    <https://agrovoc.fao.org/sparql>
    <http://meharry.eagle-i.net/sparqler/sparql>
    <https://xula.eagle-i.net/sparqler/sparql>
    <http://geo.linkeddata.es/sparql>
    <http://sparql.uniprot.org>
    <https://meharry.eagle-i.net/sparqler/sparql>
    <https://www.snik.eu/sparql>
    <http://cau.eagle-i.net/sparqler/sparql>
    <http://psm.eagle-i.net/sparqler/sparql>
    <http://datos.bcn.cl/sparql>
    <https://hawaii.eagle-i.net/sparqler/sparql>
    <http://data.ordnancesurvey.co.uk/datasets/os-linked-data/apis/sparql>
    <https://data.cinematheque.qc.ca/sparql>
    <http://colil.dbcls.jp/sparql>
    <http://sparql.southgreen.fr/>
    <https://utsa.eagle-i.net/sparqler/sparql>
    <https://sparql-noipa.mef.gov.it/sparql>
    <https://sparql.omabrowser.org/sparql>
    <http://hunter-cuny.eagle-i.net/sparqler/sparql>
    <http://vulcan.cs.uga.edu/sparql>
    <https://zbw.eu/beta/sparql/econ_corp/query>
    <https://ld.cultural.jp/sparql>
    <https://zbw.eu/beta/sparql/pm20/query>
    <http://lod.openaire.eu/sparql>
    <https://digits2.mainzed.org/covid19/sparql>
    <https://io.datascience-paris-saclay.fr/sparql>
    <https://data.nationallibrary.fi/bib/sparql>
    <http://rdf.disgenet.org/sparql/>
    <https://opendata.mfcr.cz/lod/sparql>
    <http://agrovoc.uniroma2.it/sparql>
    <http://zbw.eu/beta/sparql/stw/query>
    <http://genome.microbedb.jp/sparql>
    <http://data.cervantesvirtual.com/sparql>
    <http://id.nlm.nih.gov/mesh/sparql>
    <https://lingualibre.org/bigdata/namespace/wdq/sparql>
    <http://data.allie.dbcls.jp/sparql>
    <http://vocabs.ands.org.au/repository/api/sparql/csiro_international-chronostratigraphic-chart_2018>
    <http://ldf.fi/folklore/sparql>
    <https://ldf.fi/mufi/sparql>
    <http://sparql.wikipathways.org/sparql>
    <http://publications.europa.eu/webapi/rdf/sparql>
    <https://bgee.org/sparql>
    <http://opendata.aragon.es/sparql>
    <https://api.data.muziekweb.nl/datasets/muziekweborganization/Muziekweb/services/Muziekweb/sparql>
    <http://ohsu.eagle-i.net/sparqler/sparql>
    <http://ja.dbpedia.org/sparql>
    <http://vocabulary.curriculum.edu.au/PoolParty/sparql/scot>
    <http://libris.kb.se/sparql>
    <http://ontology.inrae.fr/weather/sparql>
    <https://pgxlod.loria.fr/sparql>
    <http://webenemasuno.linkeddata.es/sparql>
    <https://data.ordnancesurvey.co.uk/datasets/os-linked-data/apis/sparql>
    <http://xula.eagle-i.net/sparqler/sparql>
    <http://sparql.hegroup.org/sparql/>
    <http://uccaribe.eagle-i.net/sparqler/sparql>
    <https://psm.eagle-i.net/sparqler/sparql>
    <http://kaiko.getalp.org/sparql>
    <http://www.orpha.net/sparql>
    <http://semanticweb.cs.vu.nl/dss/sparql/>
    <http://data.logainm.ie/sparql>
    <http://147.100.179.235:8082/blazegraph/namespace/AnaEE_sites/sparql>
    <https://alma.uni.lu/sparql>
    <https://dba-rdf.biosciencedbc.jp/sparql>
    <https://ccny-cuny.eagle-i.net/sparqler/sparql>
    <https://howard.eagle-i.net/sparqler/sparql>
    <http://lsd.dbcls.jp/sparql>
    <http://de.dbpedia.org/sparql>
    <https://isidore.science/sparql>
    <https://sparql.proconsortium.org/virtuoso/sparql>
    <http://datos.bne.es/sparql>
    <http://bio2rdf.org/sparql>
    <http://vocab.getty.edu/sparql>
    <http://wasabi.inria.fr/sparql>
    <https://colil.dbcls.jp/sparql>
    <https://www.orpha.net/sparql>
    <http://semanticweb.cs.vu.nl/iati/sparql/>
    <http://linkeddata.uriburner.com/sparql/>
    <http://msm.eagle-i.net/sparqler/sparql>
    <http://semanticweb.cs.vu.nl/verrijktkoninkrijk/sparql/>
    <https://sparql.glycoinfo.org/sparql>
    <https://hamap.expasy.org/sparql/>
    <http://eu.dbpedia.org/sparql>
    <http://famu.eagle-i.net/sparqler/sparql>
    <http://onto.fel.cvut.cz/rdf4j-server/repositories/ufo-current>
    <http://ccny-cuny.eagle-i.net/sparqler/sparql>
    <http://utsa.eagle-i.net/sparqler/sparql>
    <https://ideal-rdf.dbcls.jp/sparql>
    <http://montana.eagle-i.net/sparqler/sparql>
    <https://taxref.mnhn.fr/sparql>
    <http://alaska.eagle-i.net/sparqler/sparql>
    <https://query.wikidata.org/bigdata/namespace/wdq/sparql>
    <http://ct-linkdata.aegean.gr/gcam/sparql>
    <http://tuskegee.eagle-i.net/sparqler/sparql>
    <http://colinda.org/endpoint.php>
    <http://fr.dbpedia.org/sparql>
    <http://dbpedia.org/sparql>
    <https://hu.dbpedia.org/sparql/>
    <http://ontology.inrae.fr/frenchcropusage/query>
    <http://factforge.net/repositories/ff-news>
    <http://navi.first.lifesciencedb.jp/fanavi/sparql>
    <http://hawaii.eagle-i.net/sparqler/sparql>
    <http://dati.beniculturali.it/sparql>
    <http://es.dbpedia.org/sparql>
    <http://jsu.eagle-i.net/sparqler/sparql>
    <https://ruian.linked.opendata.cz/sparql>
    <http://www.scholarlydata.org/sparql/>
    <http://ldf.fi/kirjasampo/sparql>
    <http://serendipity.utpl.edu.ec/lod/sparql>
    <http://www.foodie-cloud.org/sparql>
    <https://covidontheweb.inria.fr/sparql>
    <https://linked.opendata.cz/sparql>
    <http://prod-dekalog.inria.fr/sparql>
    <http://ldf.fi/warsa/sparql>
    <https://dbpedia.org/sparql>
    <http://id.dbpedia.org/sparql>
    <http://ldf.fi/ww1lod/sparql>
    <http://caligraph.org/sparql>
    <http://sparql.europeana.eu>
    <http://linked.opendata.cz/sparql>
    <http://el.dbpedia.org/sparql>
    <http://nl.dbpedia.org/sparql>
    <https://linkedwiki.com/sparql>
    <http://ld.cultural.jp/sparql>
    <http://ko.dbpedia.org/sparql>
    <http://sparql.omabrowser.org/sparql>
    <http://ontology.inrae.fr/bsv/sparql>
    <http://data.ordnancesurvey.co.uk/datasets/opennames/apis/sparql>
    <http://zbw.eu/beta/sparql/stwv/query>
    <http://ontology.irstea.fr/weather/sparql>
    <http://sparql-noipa.mef.gov.it/sparql>
    <http://alma.uni.lu/sparql>
    <http://jpsearch.go.jp/rdf/sparql/>
    <http://www.orkg.org/orkg/triplestore>
    <http://webisa.webdatacommons.org/sparql>
    <http://sparql.uniprot.org/sparql>
    <http://ldf.fi/mufi/sparql>
    <https://eu.dbpedia.org/sparql>
    <http://data.escr.fr/sparql>
    <http://forum.semantic-metabolomics.fr/sparql/>
    <http://zbw.eu/beta/sparql/econ_corp/query>
    <http://opendata.mfcr.cz/lod/sparql>
    <http://dydra.com/markw/polyadenylation-sites-in-magnaporthe-oryza/sparql>
    <http://taxref.mnhn.fr/sparql>
    <http://data.ordnancesurvey.co.uk/datasets/50k-gazetteer/apis/sparql>
    <http://data.cssz.cz/sparql>
    <http://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/cht>
    <http://ontology.inrae.fr/frenchcropusage/sparql>
    <http://aopwiki.rdf.bigcat-bioinformatics.org/sparql>
    <http://rdf.metanetx.org/sparql>
    <http://data.ordnancesurvey.co.uk/datasets/boundary-line/apis/sparql>
    <http://linkeddata1.calcul.u-psud.fr/sparql>
    <http://taxref-graphdb.i3s.unice.fr/repositories/geco>
    <http://bgee.org/sparql>
    <http://ontology.inrae.fr/bsv_test/sparql>
    <http://dbkwik.webdatacommons.org/sparql>
    <http://sparql.proconsortium.org/virtuoso/sparql>
    <http://linkedspending.aksw.org/sparql>
    <http://dbpedia-ca.upf.edu/sparql/>
    <https://rdf.metanetx.org/sparql>
    <http://lov.linkeddata.es/dataset/lov/sparql>
    <http://sparql.rhea-db.org/sparql>
    <http://zbw.eu/beta/sparql/econ_pers/query>
    <http://ico.iate.inra.fr/fuseki/ontology/query>
    <http://rdf.insee.fr/sparql>
    <http://sparql.glycoinfo.org/sparql>
    <http://ontology.inrae.fr/ppdo/sparql>
    <http://dba-rdf.biosciencedbc.jp/sparql>
    <http://ico.iate.inra.fr/fuseki/annotation/query>
    <http://api.cooperationdatabank.org/datasets/coda/databank/services/databank/sparql>
    <http://covidontheweb.inria.fr/sparql>
    <http://query.wikidata.org/bigdata/namespace/wdq/sparql>
    <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/cht>
    <http://metadb.riken.jp/sparql>
    <http://data.muziekweb.nl/MuziekwebOrganization/Muziekweb/sparql/Muziekweb>
    <http://ts.glycosmos.org/sparql>
    <http://sparql.nextprot.org/>
    <http://hamap.expasy.org/sparql/>
    <http://www.snik.eu/sparql>
    <https://dydra.com/markw/polyadenylation-sites-in-magnaporthe-oryza/sparql>
    <http://api.data.muziekweb.nl/datasets/muziekweborganization/Muziekweb/services/Muziekweb/sparql>
    <http://zbw.eu/beta/sparql/pm20/query>
    <http://db.artsdata.ca/repositories/artsdata>
    <http://hu.dbpedia.org/sparql/>
    <http://data.ordnancesurvey.co.uk/datasets/code-point-open/apis/sparql>
    <http://api.parliament.uk/sparql>
    <http://www.govdata.de/sparql>
    <http://data.idref.fr/sparql>
    <http://glyconnect.expasy.org/sparql>
    <http://eagle-i.itmat.upenn.edu/sparqler/sparql>
    <http://agrovoc.fao.org/sparql>
    <https://api.cooperationdatabank.org/datasets/coda/databank/services/databank/sparql>
    <http://ruian.linked.opendata.cz/sparql>
    <http://digits2.mainzed.org/covid19/sparql>
    <http://vocab.nerc.ac.uk/sparql/>
    <http://ideal-rdf.dbcls.jp/sparql>
    <http://isidore.science/sparql>
    <http://weakg.i3s.unice.fr/sparql>
    <http://pgxlod.loria.fr/sparql>
    <http://query.wikidata.org/sparql>
    <https://eagle-i.itmat.upenn.edu/sparqler/sparql>
  }
}
#  FILTER(CONTAINS(str(?g), "LOD-Cloud"))
  BIND(Iri(CONCAT("http://ns.inria.fr/kg/index#", MD5(str(?endpointUrl)), "KB")) AS ?kbNode)
}
